### PR TITLE
Fixes #162

### LINKED ISSUE #162: _ftelli64 does not compile on Windows when using zig cc (clang, mingw64)
I hit a compile error when compiling with zig cc - ```_ftelli64``` is msvc thing so the check for it should be:
```
#if defined(_WIN32) && defined(_MSC_VER)
```

Note.
zig cc by default uses clang and mingw64 so it defines ```__clang__``` and ```__GNUC__```.
On the other hand, cl-clang on Windows defines ```__clang__``` and ```_MSC_VER```.

### PR DESCRIPTION
**Pull request by michal-z**
#162

### CODE REVIEW

**Comment by zeux** [comment]
Out of curiosity, does zig cc not use ming64 includes? MinGW64 should be compatible with MSVC CRT, as such I'd expect it to expose fseeki64, see https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-crt/stdio/fseeko64.c#L133

**Comment by michal-z** [comment]
Yes, zig cc uses mingw64. But, it looks like zig version of the fseeko64.c file does not contain _ftell64i function. See: https://github.com/ziglang/zig/blob/master/lib/libc/mingw/stdio/fseeko64.c

**Comment by zeux** [comment]
Interesting, so their version has some parts of the library that are normally unique to MSVC CRT, but missing this one specifically. Thanks!

**Review by zeux — APPROVED** [review]

**Comment by michal-z** [comment]
@zeux  In mingw-w64 9.0.0 (latest) implementation of _ftelli64 has been moved to fseeki64.c file. But, zig does not include this file at all.

**Comment by michal-z** [comment]
I have submitted a PR to Zig which adds those functions. See: https://github.com/ziglang/zig/pull/9766

So, I guess we can close this PR.

**Pull request closed without merging**
