### PR TITLE
Added extras support.

### PR DESCRIPTION
**Pull request by jkuhlmann**
Fixes issue #50.

### CODE REVIEW

**Comment by zeux** [comment]
Does the start/end character range include `{` and `}`?

**Comment by zeux** [comment]
An alternative interface for cgltf_copy_extras_json would be smth like snprintf, where it would return the number of characters necessary in the buffer, and copy as much as the buffer allows - this would allow you to call this function twice, once with NULL/0 buffer to estimate the size, and once with actual buffer. Although these kinds of APIs are slightly fragile so the current one would work as well - my understanding is that you'd expect the caller to allocate `end_offset - start_offset + 1` manually?

**Comment by jkuhlmann** [comment]
The range contains the complete value behind the “extras” key. So, yes, it includes { and } if it’s an object. 

And, yes, the caller currently has to allocate that memory, i.e. the size can already be determined. I think it would be helpful though to also be able to do that via calling the function with a NULL pointer.

I’m not sure how useful it would be to get half a JSON string. That might be difficult to parse or not?

**Comment by zeux** [comment]
Half of a JSON string isn’t useful - I was mentioning this mostly because that’s what strncpy would do. Feel free to disregard as anything would work okay here as the size is easy to compute from offsets.

**Comment by jkuhlmann** [comment]
You're right. It's better to stick to how similar functions work. I'll change the behavior.

Thanks for the feedback!

**Pull request merged**
