### PR TITLE
Add support for KHR_materials_anisotropy

### PR DESCRIPTION
**Pull request by abwood**
This PR is following the evolution of the [KHR_materials_anisotropy](https://github.com/KhronosGroup/glTF/tree/KHR_materials_anisotropy/extensions/2.0/Khronos/KHR_materials_anisotropy) specification.

This specification is still in draft form, so this PR is not yet ready for merge. Wanted a solution available for implementers to assess in their own renderers.

### CODE REVIEW

**Comment by zeux** [comment]
Looks like the extension just got merged into glTF mainline. I looked at the change and it seems like it reflects the final version of the spec?

**Comment by zeux** [comment]
I've tested this as part of https://github.com/zeux/meshoptimizer/pull/556 and it seems to work (the parsing part at least, gltfpack doesn't use cgltf_write)

**Comment by zeux** [comment]
Oh, this is missing calls to `cgltf_free_texture_view` in `cgltf_free`. With #118 we will be able to remove those but they are necessary for now.

**Comment by zeux** [comment]
Note, the failing build is unrelated to this change - fixed by #216.

**Review by zeux — APPROVED** [review]

**Comment by jkuhlmann** [comment]
@abwood  Would you mind merging in `master` again?

**Pull request merged**
