### PR TITLE
Implement support for EXT_texture_webp

### PR DESCRIPTION
**Pull request by bobbens**
Specification:
https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_texture_webp

### CODE REVIEW

**Comment by bobbens** [comment]
Oops, it's EXT_texture_webp, not KHR_texture_webp.

**Comment by zeux** [comment]
This needs to be structured like KHR_texture_basisu; the current implementation for example doesn’t support specifying both png and webp images. Also missing cgltf_write support.

**Comment by bobbens** [comment]
> This needs to be structured like KHR_texture_basisu; the current implementation for example doesn’t support specifying both png and webp images. Also missing cgltf_write support.

How does it look now?

**Review by zeux — APPROVED** [review]

**Review by zeux — CHANGES_REQUESTED** [review]
Oh, one more thing - this needs a call to CGLTF_PTRFIXUP in cgltf_fixup_pointers for the newly added pointer field.

**Comment by bobbens** [comment]
I added a call to CGLTF_PTRFIXUP in cgltf_fixup_pointers. Hopefully should be fine now.

**Comment by zeux** [comment]
And one more thing :sweat_smile: I think this is missing writing the appropriate extension name in `cgltf_write_extensions`, so a written file with webp extension will be considered invalid by glTF spec (although this would not necessarily interfere with loading it).

**Comment by bobbens** [comment]
Lots of things I missed when grepping. Completed now perhaps.

**Review by zeux — APPROVED** [review]
Thanks! I've confirmed the parsing works in gltfpack (can't confirm cgltf_write changes since gltfpack doesn't use this but should be good on inspection). cc @jkuhlmann

**Pull request merged**
